<?php

$xls_column_ary = array(

	"PRODUCT_LIST" => array(
		array("is_use" => true, "col" => "product_name", "name" => "상품명", "width" => 40),
		array("is_use" => true, "col" => "product_idx", "name" => "상품코드", "width" => 21),
		//array("is_use" => true, "col" => "product_image", "name" => "이미지", "width" => 21),
		array("is_use" => true, "col" => "product_soldout", "name" => "품절", "width" => 21),
		array("is_use" => true, "col" => "product_sale_type", "name" => "판매타입", "width" => 21),
		array("is_use" => true, "col" => "category_name_full", "name" => "카테고리", "width" => 21),
		array("is_use" => true, "col" => "supplier_name", "name" => "공급처", "width" => 32),
		array("is_use" => true, "col" => "product_supplier_name", "name" => "공급처상품명", "width" => 32),
		array("is_use" => true, "col" => "product_regdate", "name" => "등록일", "width" => 32),
		array("is_use" => true, "col" => "product_vendor_show", "name" => "벤더사노출", "width" => 21),
	),
	"PRODUCT_OPTION_LIST" => array(
		array("is_use" => true, "col" => "product_option_name", "name" => "옵션", "width" => 40),
		array("is_use" => true, "col" => "product_option_idx", "name" => "옵션코드", "width" => 21),
		array("is_use" => true, "col" => "product_option_purchase_price", "name" => "매입가", "width" => 21, "data_type" => "number"),
		array("is_use" => true, "col" => "product_option_sale_price_A", "name" => "판매가 A", "width" => 21, "data_type" => "number"),
		array("is_use" => true, "col" => "product_option_sale_price_B", "name" => "판매가 B", "width" => 21, "data_type" => "number"),
		array("is_use" => true, "col" => "product_option_sale_price_C", "name" => "판매가 C", "width" => 21, "data_type" => "number"),
		array("is_use" => true, "col" => "product_option_sale_price_D", "name" => "판매가 D", "width" => 21, "data_type" => "number"),
		array("is_use" => true, "col" => "product_option_sale_price_E", "name" => "판매가 E", "width" => 21, "data_type" => "number"),
		array("is_use" => true, "col" => "product_option_warning_count", "name" => "경고수량", "width" => 21),
		array("is_use" => true, "col" => "product_option_danger_count", "name" => "위험수량", "width" => 21),
		array("is_use" => true, "col" => "product_option_regdate", "name" => "옵션등록일", "width" => 32),
	),
	"ORDER_SEARCH_LIST" => array(
		array("is_use" => true, "col" => "order_progress_step_accept_temp_date", "name" => "가접수시간", "width" => 23),
		array("is_use" => true, "col" => "order_progress_step_accept_date", "name" => "접수시간", "width" => 23),
		array("is_use" => true, "col" => "order_pay_date", "name" => "주문일", "width" => 23),
		array("is_use" => true, "col" => "order_idx", "name" => "관리번호", "width" => 16),
		array("is_use" => true, "col" => "seller_name", "name" => "판매처", "width" => 26),
		array("is_use" => true, "col" => "receive_name", "name" => "수령자 이름", "width" => 18),
		array("is_use" => true, "col" => "receive_tp_num", "name" => "수령자 연락처", "width" => 18),
		array("is_use" => true, "col" => "receive_hp_num", "name" => "수령자 휴대폰", "width" => 18),
		array("is_use" => true, "col" => "receive_zipcode", "name" => "수령자 우편번호", "width" => 12),
		array("is_use" => true, "col" => "receive_addr", "name" => "수령자 주소", "width" => 80),
		array("is_use" => true, "col" => "receive_memo", "name" => "배송메시지", "width" => 40),
		array("is_use" => true, "col" => "product_name", "name" => "상품명", "width" => 40),
		array("is_use" => true, "col" => "product_option_name", "name" => "옵션", "width" => 30),
		array("is_use" => true, "col" => "product_option_cnt", "name" => "수량", "width" => 18, "data_type" => "number"),
		array("is_use" => true, "col" => "product_option_sale_price", "name" => "가격", "width" => 18, "data_type" => "number"),
		array("is_use" => true, "col" => "supplier_name", "name" => "공급처", "width" => 21),
		array("is_use" => true, "col" => "current_stock_amount", "name" => "현 재고", "width" => 21, "data_type" => "number"),
		array("is_use" => true, "col" => "order_progress_step_han", "name" => "상태", "width" => 21),
		array("is_use" => true, "col" => "market_order_no", "name" => "주문번호", "width" => 21),
		array("is_use" => true, "col" => "invoice_date", "name" => "송장입력일", "width" => 23),
		array("is_use" => true, "col" => "invoice_no", "name" => "송장번호", "width" => 21),
		array("is_use" => true, "col" => "shipping_date", "name" => "배송일", "width" => 23),
		array("is_use" => true, "col" => "market_product_no", "name" => "판매처 상품코드", "width" => 21),
	),
	"STOCK_PRODUCT_LIST" => array(
		array("is_use" => true, "col" => "supplier_name", "name" => "공급처", "width" => 30),
		array("is_use" => true, "col" => "product_idx", "name" => "상품코드", "width" => 18),
		array("is_use" => true, "col" => "product_option_idx", "name" => "옵션코드", "width" => 18),
		array("is_use" => true, "col" => "product_name", "name" => "상품명", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "product_option_name", "name" => "옵션", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "stock_unit_price", "name" => "원가", "width" => 32, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_NORMAL", "name" => "정상재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_price_NORMAL", "name" => "정상재고금액", "width" => 32, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_BAD", "name" => "불량재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_price_BAD", "name" => "불량재고금액", "width" => 32, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_BAD_OUT_EXCHANGE", "name" => "불량재고-교환출고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_BAD_OUT_RETURN", "name" => "불량재고-반품출고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_ABNORMAL", "name" => "양품재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_HOLD", "name" => "보류", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_FAC_RETURN_EXCHNAGE", "name" => "출고지회송-교환회송", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_FAC_RETURN_BACK", "name" => "출고지회송-반품회송", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_LOSS", "name" => "분실재고", "width" => 23, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_DISPOSAL", "name" => "일반폐기", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_DISPOSAL_PERMANENT", "name" => "영구폐기", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_INVOICE", "name" => "미배송(송장)", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_ACCEPT", "name" => "미배송(접수)", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "product_option_warning_count", "name" => "재고위협수량", "width" => 26, "data_type" => "number", "halign" => "right"),
	),
	"STOCK_LIST" => array(
		array("is_use" => true, "col" => "supplier_name", "name" => "공급처", "width" => 30),
		array("is_use" => true, "col" => "product_idx", "name" => "상품코드", "width" => 18),
		array("is_use" => true, "col" => "product_option_idx", "name" => "옵션코드", "width" => 18),
		array("is_use" => true, "col" => "product_name", "name" => "상품명", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "product_option_name", "name" => "옵션", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "stock_amount_SHIPPED", "name" => "배송", "width" => 32, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_NORMAL", "name" => "정상재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_BAD", "name" => "불량재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_BAD_OUT_EXCHANGE", "name" => "불량재고-교환출고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_BAD_OUT_RETURN", "name" => "불량재고-반품출고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_ABNORMAL", "name" => "양품재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_HOLD", "name" => "보류", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_FAC_RETURN_EXCHNAGE", "name" => "출고지회송-교환회송", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_FAC_RETURN_BACK", "name" => "출고지회송-반품회송", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_LOSS", "name" => "분실재고", "width" => 23, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_DISPOSAL", "name" => "일반폐기", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_DISPOSAL_PERMANENT", "name" => "영구폐기", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_INVOICE", "name" => "송장", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_ACCEPT", "name" => "접수", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "product_option_warning_count", "name" => "재고위협수량", "width" => 26, "data_type" => "number", "halign" => "right"),
	),
	"STOCK_PERIOD_LIST" => array(
		array("is_use" => true, "col" => "supplier_name", "name" => "공급처", "width" => 30),
		array("is_use" => true, "col" => "product_idx", "name" => "상품코드", "width" => 18),
		array("is_use" => true, "col" => "product_option_idx", "name" => "옵션코드", "width" => 18),
		array("is_use" => true, "col" => "product_name", "name" => "상품명", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "product_option_name", "name" => "옵션", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "stock_unit_price", "name" => "원가", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "product_option_sale_price", "name" => "판매가", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_unit_price_sum", "name" => "원가합", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_NORMAL", "name" => "현재 정상재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_BAD", "name" => "현재 불량재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_BAD_OUT_EXCHANGE", "name" => "현재 불량재고-교환출고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_BAD_OUT_RETURN", "name" => "현재 불량재고-반품출고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_ABNORMAL", "name" => "현재 양품재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_FAC_RETURN_EXCHNAGE", "name" => "현재 출고지회송-교환회송", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_FAC_RETURN_BACK", "name" => "현재 출고지회송-반품회송", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_LOSS", "name" => "현재 분실재고", "width" => 23, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_DISPOSAL", "name" => "현재 일반폐기", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_DISPOSAL_PERMANENT", "name" => "현재 영구폐기", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_IN", "name" => "입고", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_price_IN", "name" => "입고금액", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_RETURN", "name" => "반품", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_price_RETURN", "name" => "반품금액", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_OUT", "name" => "출고", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_price_OUT", "name" => "출고금액", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_INVOICE", "name" => "송장", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_price_INVOICE", "name" => "송장금액", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_SHIPPED", "name" => "배송", "width" => 26, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_price_SHIPPED", "name" => "배송금액", "width" => 26, "data_type" => "number", "halign" => "right"),
	),
	"STOCK_DAILY_LIST" => array(
		array("is_use" => true, "col" => "supplier_name", "name" => "공급처", "width" => 30),
		array("is_use" => true, "col" => "product_idx", "name" => "상품코드", "width" => 18),
		array("is_use" => true, "col" => "product_option_idx", "name" => "옵션코드", "width" => 18),
		array("is_use" => true, "col" => "product_name", "name" => "상품명", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "product_option_name", "name" => "옵션", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "stock_unit_price", "name" => "원가", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_NORMAL", "name" => "현재 정상재고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_OUT", "name" => "기간 배송", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_INVOICE_AVG", "name" => "조회기간-평균송장", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_IN_AVG", "name" => "조회기간-평균입고", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_SHIPPED_AVG", "name" => "조회기간-평균배송", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_INVOICE_prevweek_AVG", "name" => "직전7일-평균송장", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_spend", "name" => "소진일", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_IN", "name" => "입고 MM/DD~MM/DD", "width" => 21, "data_type" => "number", "halign" => "right", "is_readonly" => true),
		array("is_use" => true, "col" => "stock_amount_STOCKORDER", "name" => "입고대기(발주)", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount_ORDER_STOCKIN", "name" => "입고대기(CS)", "width" => 21, "data_type" => "number", "halign" => "right"),
	),
	"STOCK_CONFIRM_LIST" => array(
		array("is_use" => true, "col" => "stock_kind_han", "name" => "구분", "width" => 30),
		array("is_use" => true, "col" => "stock_order_idx", "name" => "코드", "width" => 18),
		array("is_use" => true, "col" => "stock_request_date2", "name" => "생성일", "width" => 32),
		array("is_use" => true, "col" => "stock_in_date", "name" => "입고일", "width" => 32),
		array("is_use" => true, "col" => "member_id", "name" => "작업자", "width" => 12),
		array("is_use" => true, "col" => "supplier_name", "name" => "공급처", "width" => 18),
		array("is_use" => true, "col" => "product_idx", "name" => "상품코드", "width" => 18),
		array("is_use" => true, "col" => "product_option_idx", "name" => "옵션코드", "width" => 18),
		array("is_use" => true, "col" => "product_name", "name" => "상품명", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "product_option_name", "name" => "옵션", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "stock_unit_price", "name" => "원가", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "order_info", "name" => "구매자정보", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "stock_due_amount", "name" => "예정수량", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_amount", "name" => "입고수량", "width" => 21, "data_type" => "number", "halign" => "right"),
		array("is_use" => true, "col" => "stock_status_name", "name" => "상태", "width" => 12, "halign" => "center"),
		array("is_use" => true, "col" => "stock_msg", "name" => "메모", "width" => 60, "halign" => "left"),
		array("is_use" => true, "col" => "stock_is_confirm_han", "name" => "입고확정", "width" => 12)
	)


);

?>